

-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Booking"
(
    booking_id integer NOT NULL,
    guest_id integer NOT NULL,
    room_id integer NOT NULL,
    check_in_date date NOT NULL,
    check_out_date date NOT NULL,
    CONSTRAINT "Booking_pkey" PRIMARY KEY (booking_id)
);

CREATE TABLE IF NOT EXISTS public."Guest"
(
    guest_id integer NOT NULL,
    full_name character varying COLLATE pg_catalog."default" NOT NULL,
    phone character varying COLLATE pg_catalog."default" NOT NULL,
    email character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Guest_pkey" PRIMARY KEY (guest_id)
);

CREATE TABLE IF NOT EXISTS public."Room"
(
    room_id integer NOT NULL,
    room_number character varying COLLATE pg_catalog."default" NOT NULL,
    type_id integer NOT NULL,
    CONSTRAINT "Room_pkey" PRIMARY KEY (room_id)
);

CREATE TABLE IF NOT EXISTS public."Room_type"
(
    type_id integer NOT NULL,
    type_name character varying COLLATE pg_catalog."default" NOT NULL,
    price_per_night character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Room_type_pkey" PRIMARY KEY (type_id)
);

ALTER TABLE IF EXISTS public."Booking"
    ADD FOREIGN KEY (guest_id)
    REFERENCES public."Guest" (guest_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Booking"
    ADD FOREIGN KEY (room_id)
    REFERENCES public."Room" (room_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Room"
    ADD FOREIGN KEY (type_id)
    REFERENCES public."Room_type" (type_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;